// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See VVortex.h for the primary calling header

#include "verilated.h"
#include "verilated_dpi.h"

#include "VVortex_VX_fpu_dpi__N2_T2_O1.h"

VL_ATTR_COLD void VVortex_VX_fpu_dpi__N2_T2_O1___initial__TOP__Vortex__genblk5__BRA__0__KET____DOT__cluster__DOT__genblk4__BRA__0__KET____DOT__socket__DOT__genblk6__BRA__0__KET____DOT__core__DOT__execute__DOT__fpu_unit__DOT__genblk1__BRA__0__KET____DOT__fpu_dpi__0(VVortex_VX_fpu_dpi__N2_T2_O1* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    VVortex__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+                  VVortex_VX_fpu_dpi__N2_T2_O1___initial__TOP__Vortex__genblk5__BRA__0__KET____DOT__cluster__DOT__genblk4__BRA__0__KET____DOT__socket__DOT__genblk6__BRA__0__KET____DOT__core__DOT__execute__DOT__fpu_unit__DOT__genblk1__BRA__0__KET____DOT__fpu_dpi__0\n"); );
    // Init
    VlWide<3>/*95:0*/ __Vtemp_h34a6d6f0__0;
    VlWide<3>/*95:0*/ __Vtemp_h34a6d6f0__1;
    // Body
    VL_RAND_RESET_W(72, __Vtemp_h34a6d6f0__0);
    vlSelf->rsp_arb__DOT____Vxrand_h7e15b196__0[0U] 
        = __Vtemp_h34a6d6f0__0[0U];
    vlSelf->rsp_arb__DOT____Vxrand_h7e15b196__0[1U] 
        = __Vtemp_h34a6d6f0__0[1U];
    vlSelf->rsp_arb__DOT____Vxrand_h7e15b196__0[2U] 
        = (0xffU & __Vtemp_h34a6d6f0__0[2U]);
    vlSelf->__Vxrand_h66cc2c69__0 = VL_RAND_RESET_Q(64);
    vlSelf->__Vxrand_h9b57f0ef__0 = (0x3ffU & VL_RAND_RESET_I(10));
    VL_RAND_RESET_W(72, __Vtemp_h34a6d6f0__1);
    vlSelf->div_sqrt_arb__DOT____Vxrand_h7e15b196__0[0U] 
        = __Vtemp_h34a6d6f0__1[0U];
    vlSelf->div_sqrt_arb__DOT____Vxrand_h7e15b196__0[1U] 
        = __Vtemp_h34a6d6f0__1[1U];
    vlSelf->div_sqrt_arb__DOT____Vxrand_h7e15b196__0[2U] 
        = (0xffU & __Vtemp_h34a6d6f0__1[2U]);
    vlSelf->fma__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fma__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fdiv__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fdiv__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fcvt__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fcvt__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fncp__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fncp__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 
        = (1U & VL_RAND_RESET_I(1));
}

VL_ATTR_COLD void VVortex_VX_fpu_dpi__N2_T2_O1___ctor_var_reset(VVortex_VX_fpu_dpi__N2_T2_O1* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    VVortex__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+                  VVortex_VX_fpu_dpi__N2_T2_O1___ctor_var_reset\n"); );
    // Body
    vlSelf->__Vxrand_h9b57f0ef__0 = VL_RAND_RESET_I(10);
    vlSelf->__Vxrand_h66cc2c69__0 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__clk = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reset = VL_RAND_RESET_I(1);
    vlSelf->__PVT__valid_in = VL_RAND_RESET_I(1);
    vlSelf->__PVT__ready_in = VL_RAND_RESET_I(1);
    vlSelf->__PVT__lane_mask = VL_RAND_RESET_I(2);
    vlSelf->__PVT__tag_in = VL_RAND_RESET_I(2);
    vlSelf->__PVT__op_type = VL_RAND_RESET_I(4);
    vlSelf->__PVT__fmt = VL_RAND_RESET_I(2);
    vlSelf->__PVT__frm = VL_RAND_RESET_I(3);
    vlSelf->__PVT__dataa = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__datab = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__datac = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__result = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__has_fflags = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fflags = VL_RAND_RESET_I(5);
    vlSelf->__PVT__tag_out = VL_RAND_RESET_I(2);
    vlSelf->__PVT__ready_out = VL_RAND_RESET_I(1);
    vlSelf->__PVT__valid_out = VL_RAND_RESET_I(1);
    vlSelf->__PVT__per_core_ready_in = VL_RAND_RESET_I(4);
    VL_RAND_RESET_W(256, vlSelf->__PVT__per_core_result);
    vlSelf->__PVT__per_core_tag_out = VL_RAND_RESET_I(8);
    vlSelf->__PVT__per_core_ready_out = VL_RAND_RESET_I(4);
    vlSelf->__PVT__per_core_valid_out = VL_RAND_RESET_I(4);
    vlSelf->__PVT__per_core_has_fflags = VL_RAND_RESET_I(4);
    vlSelf->__PVT__per_core_fflags = VL_RAND_RESET_I(20);
    vlSelf->__PVT__core_select = VL_RAND_RESET_I(2);
    vlSelf->__PVT__is_fadd = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fsub = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fmul = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fmadd = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fmsub = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fnmadd = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fnmsub = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_div = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fcmp = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_itof = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_utof = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_ftoi = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_ftou = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_f2f = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dst_fmt = VL_RAND_RESET_I(1);
    vlSelf->__PVT__int_fmt = VL_RAND_RESET_I(1);
    for (int __Vi0=0; __Vi0<3; ++__Vi0) {
        VL_RAND_RESET_W(128, vlSelf->__PVT__operands[__Vi0]);
    }
    vlSelf->__Vcellout__div_sqrt_arb__ready_in = VL_RAND_RESET_I(2);
    vlSelf->__Vcellinp__div_sqrt_arb__valid_in = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(288, vlSelf->__PVT__per_core_data_out);
    vlSelf->__PVT__fma__DOT__result_fma = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fma__DOT__result_fadd);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fma__DOT__result_fsub);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fma__DOT__result_fmul);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fma__DOT__result_fmadd);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fma__DOT__result_fmsub);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fma__DOT__result_fnmadd);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fma__DOT__result_fnmsub);
    vlSelf->__PVT__fma__DOT__fflags_fma = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fma__DOT__fflags_fadd = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fma__DOT__fflags_fsub = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fma__DOT__fflags_fmul = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fma__DOT__fflags_fmadd = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fma__DOT__fflags_fmsub = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fma__DOT__fflags_fnmadd = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fma__DOT__fflags_fnmsub = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fma__DOT__fma_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fma__DOT__fma_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fma__DOT__fma_fire = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fma__DOT_____05Ffflags_merged = VL_RAND_RESET_I(5);
    vlSelf->__PVT__fdiv__DOT__result_fdiv_r = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fdiv__DOT__result_fdiv);
    vlSelf->__PVT__fdiv__DOT__fflags_fdiv = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fdiv__DOT__fdiv_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fdiv__DOT__fdiv_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fdiv__DOT__fdiv_fire = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fdiv__DOT_____05Ffflags_merged = VL_RAND_RESET_I(5);
    vlSelf->__PVT__fsqrt__DOT__result_fsqrt_r = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fsqrt__DOT__result_fsqrt);
    vlSelf->__PVT__fsqrt__DOT__fflags_fsqrt = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fsqrt__DOT__fsqrt_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fsqrt__DOT__fsqrt_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fsqrt__DOT__fsqrt_fire = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fsqrt__DOT_____05Ffflags_merged = VL_RAND_RESET_I(5);
    vlSelf->__PVT__fcvt__DOT__result_fcvt = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fcvt__DOT__result_itof);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fcvt__DOT__result_utof);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fcvt__DOT__result_ftoi);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fcvt__DOT__result_ftou);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fcvt__DOT__result_f2f);
    vlSelf->__PVT__fcvt__DOT__fflags_fcvt = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fcvt__DOT__fflags_itof = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fcvt__DOT__fflags_utof = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fcvt__DOT__fflags_ftoi = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fcvt__DOT__fflags_ftou = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fcvt__DOT__fcvt_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fcvt__DOT__fcvt_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fcvt__DOT__fcvt_fire = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fcvt__DOT_____05Ffflags_merged = VL_RAND_RESET_I(5);
    vlSelf->__PVT__fncp__DOT__result_fncp = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fncp__DOT__result_fclss);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fncp__DOT__result_flt);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fncp__DOT__result_fle);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fncp__DOT__result_feq);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fncp__DOT__result_fmin);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fncp__DOT__result_fmax);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fncp__DOT__result_fsgnj);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fncp__DOT__result_fsgnjn);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fncp__DOT__result_fsgnjx);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fncp__DOT__result_fmvx);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fncp__DOT__result_fmvf);
    vlSelf->__PVT__fncp__DOT__fflags_fncp = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fncp__DOT__fflags_flt = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fncp__DOT__fflags_fle = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fncp__DOT__fflags_feq = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fncp__DOT__fflags_fmin = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fncp__DOT__fflags_fmax = VL_RAND_RESET_I(10);
    vlSelf->__PVT__fncp__DOT__fncp_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fncp__DOT__fncp_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fncp__DOT__fncp_fire = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fncp__DOT_____05Ffflags_merged = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_hd0358701__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h3e5a0693__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_hbdab4cf9__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h57c9cc29__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h6d7b0f8b__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_hf5e73f0f__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h33426f81__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h52a87fc1__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h00b0650d__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h23046ae6__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h2e9bfe6a__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h4bd064b9__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h29370721__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h2849bae9__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h602015d0__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h211fabc7__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h56f728ba__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h6f32243e__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h2a86cb7b__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_hbbf976b3__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h5881caf4__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h5881caf4__1 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h5881caf4__2 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h5881caf4__3 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h5881caf4__4 = VL_RAND_RESET_I(5);
    VL_RAND_RESET_W(72, vlSelf->div_sqrt_arb__DOT____Vxrand_h7e15b196__0);
    VL_RAND_RESET_W(73, vlSelf->div_sqrt_arb__DOT____Vcellinp__genblk1__DOT__genblk1__DOT__out_buf__data_in);
    vlSelf->__PVT__div_sqrt_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__grant_index_r = VL_RAND_RESET_I(1);
    vlSelf->__PVT__div_sqrt_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__grant_onehot_r = VL_RAND_RESET_I(2);
    vlSelf->__PVT__div_sqrt_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__state = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(72, vlSelf->rsp_arb__DOT____Vxrand_h7e15b196__0);
    vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__grant_index_r = VL_RAND_RESET_I(2);
    vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__grant_onehot_r = VL_RAND_RESET_I(4);
    vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__state = VL_RAND_RESET_I(2);
    vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__stall = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(75, vlSelf->rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT____Vcellout__genblk1__DOT__pipe_register__data_out);
    VL_RAND_RESET_W(75, vlSelf->rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT____Vcellinp__genblk1__DOT__pipe_register__data_in);
    VL_RAND_RESET_W(74, vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__pipe_register__DOT__genblk1__DOT__genblk1__DOT__value_d);
    vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__pipe_register__DOT__genblk1__DOT__genblk1__DOT__value_r = VL_RAND_RESET_I(1);
    vlSelf->fma__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 = VL_RAND_RESET_I(1);
    vlSelf->fma__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(288, vlSelf->__PVT__fma__DOT__shift_reg__DOT__genblk1__DOT__entries);
    vlSelf->fma__DOT__shift_reg__DOT____Vlvbound_hea93ed70__0 = VL_RAND_RESET_I(1);
    vlSelf->fma__DOT__shift_reg__DOT____Vlvbound_hf17be9cf__0 = VL_RAND_RESET_I(1);
    vlSelf->fma__DOT__shift_reg__DOT____Vlvbound_h2058a6de__0 = VL_RAND_RESET_I(1);
    vlSelf->fdiv__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 = VL_RAND_RESET_I(1);
    vlSelf->fdiv__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(1080, vlSelf->__PVT__fdiv__DOT__shift_reg__DOT__genblk1__DOT__entries);
    vlSelf->fdiv__DOT__shift_reg__DOT____Vlvbound_hbac3ffee__0 = VL_RAND_RESET_I(1);
    vlSelf->fdiv__DOT__shift_reg__DOT____Vlvbound_hcd3d2dfb__0 = VL_RAND_RESET_I(1);
    vlSelf->fdiv__DOT__shift_reg__DOT____Vlvbound_h503d6ec1__0 = VL_RAND_RESET_I(1);
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 = VL_RAND_RESET_I(1);
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(720, vlSelf->__PVT__fsqrt__DOT__shift_reg__DOT__genblk1__DOT__entries);
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vlvbound_h7a6f1169__0 = VL_RAND_RESET_I(1);
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vlvbound_hc5aee17f__0 = VL_RAND_RESET_I(1);
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vlvbound_hd60967cc__0 = VL_RAND_RESET_I(1);
    vlSelf->fcvt__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 = VL_RAND_RESET_I(1);
    vlSelf->fcvt__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(360, vlSelf->__PVT__fcvt__DOT__shift_reg__DOT__genblk1__DOT__entries);
    vlSelf->fcvt__DOT__shift_reg__DOT____Vlvbound_had9bbe87__0 = VL_RAND_RESET_I(1);
    vlSelf->fcvt__DOT__shift_reg__DOT____Vlvbound_hab636c7c__0 = VL_RAND_RESET_I(1);
    vlSelf->fcvt__DOT__shift_reg__DOT____Vlvbound_h563768aa__0 = VL_RAND_RESET_I(1);
    vlSelf->fncp__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 = VL_RAND_RESET_I(1);
    vlSelf->fncp__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(146, vlSelf->__PVT__fncp__DOT__shift_reg__DOT__genblk1__DOT__entries);
    vlSelf->fncp__DOT__shift_reg__DOT____Vlvbound_h5344c213__0 = VL_RAND_RESET_I(1);
    vlSelf->fncp__DOT__shift_reg__DOT____Vlvbound_he67dff96__0 = VL_RAND_RESET_I(1);
    vlSelf->fncp__DOT__shift_reg__DOT____Vlvbound_h33c0b887__0 = VL_RAND_RESET_I(1);
    vlSelf->__Vtask_dpi_fadd__0__result = 0;
    vlSelf->__Vtask_dpi_fadd__0__fflags = 0;
    vlSelf->__Vtask_dpi_fsub__1__result = 0;
    vlSelf->__Vtask_dpi_fsub__1__fflags = 0;
    vlSelf->__Vtask_dpi_fmul__2__result = 0;
    vlSelf->__Vtask_dpi_fmul__2__fflags = 0;
    vlSelf->__Vtask_dpi_fmadd__3__result = 0;
    vlSelf->__Vtask_dpi_fmadd__3__fflags = 0;
    vlSelf->__Vtask_dpi_fmsub__4__result = 0;
    vlSelf->__Vtask_dpi_fmsub__4__fflags = 0;
    vlSelf->__Vtask_dpi_fnmadd__5__result = 0;
    vlSelf->__Vtask_dpi_fnmadd__5__fflags = 0;
    vlSelf->__Vtask_dpi_fnmsub__6__result = 0;
    vlSelf->__Vtask_dpi_fnmsub__6__fflags = 0;
    vlSelf->__Vtask_dpi_fdiv__7__result = 0;
    vlSelf->__Vtask_dpi_fdiv__7__fflags = 0;
    vlSelf->__Vtask_dpi_fsqrt__8__result = 0;
    vlSelf->__Vtask_dpi_fsqrt__8__fflags = 0;
    vlSelf->__Vtask_dpi_itof__9__result = 0;
    vlSelf->__Vtask_dpi_itof__9__fflags = 0;
    vlSelf->__Vtask_dpi_utof__10__result = 0;
    vlSelf->__Vtask_dpi_utof__10__fflags = 0;
    vlSelf->__Vtask_dpi_ftoi__11__result = 0;
    vlSelf->__Vtask_dpi_ftoi__11__fflags = 0;
    vlSelf->__Vtask_dpi_ftou__12__result = 0;
    vlSelf->__Vtask_dpi_ftou__12__fflags = 0;
    vlSelf->__Vtask_dpi_f2f__13__result = 0;
    vlSelf->__Vtask_dpi_fclss__14__result = 0;
    vlSelf->__Vtask_dpi_fle__15__result = 0;
    vlSelf->__Vtask_dpi_fle__15__fflags = 0;
    vlSelf->__Vtask_dpi_flt__16__result = 0;
    vlSelf->__Vtask_dpi_flt__16__fflags = 0;
    vlSelf->__Vtask_dpi_feq__17__result = 0;
    vlSelf->__Vtask_dpi_feq__17__fflags = 0;
    vlSelf->__Vtask_dpi_fmin__18__result = 0;
    vlSelf->__Vtask_dpi_fmin__18__fflags = 0;
    vlSelf->__Vtask_dpi_fmax__19__result = 0;
    vlSelf->__Vtask_dpi_fmax__19__fflags = 0;
    vlSelf->__Vtask_dpi_fsgnj__20__result = 0;
    vlSelf->__Vtask_dpi_fsgnjn__21__result = 0;
    vlSelf->__Vtask_dpi_fsgnjx__22__result = 0;
    vlSelf->__Vtask_dpi_fadd__23__result = 0;
    vlSelf->__Vtask_dpi_fadd__23__fflags = 0;
    vlSelf->__Vtask_dpi_fsub__24__result = 0;
    vlSelf->__Vtask_dpi_fsub__24__fflags = 0;
    vlSelf->__Vtask_dpi_fmul__25__result = 0;
    vlSelf->__Vtask_dpi_fmul__25__fflags = 0;
    vlSelf->__Vtask_dpi_fmadd__26__result = 0;
    vlSelf->__Vtask_dpi_fmadd__26__fflags = 0;
    vlSelf->__Vtask_dpi_fmsub__27__result = 0;
    vlSelf->__Vtask_dpi_fmsub__27__fflags = 0;
    vlSelf->__Vtask_dpi_fnmadd__28__result = 0;
    vlSelf->__Vtask_dpi_fnmadd__28__fflags = 0;
    vlSelf->__Vtask_dpi_fnmsub__29__result = 0;
    vlSelf->__Vtask_dpi_fnmsub__29__fflags = 0;
    vlSelf->__Vtask_dpi_fdiv__30__result = 0;
    vlSelf->__Vtask_dpi_fdiv__30__fflags = 0;
    vlSelf->__Vtask_dpi_fsqrt__31__result = 0;
    vlSelf->__Vtask_dpi_fsqrt__31__fflags = 0;
    vlSelf->__Vtask_dpi_itof__32__result = 0;
    vlSelf->__Vtask_dpi_itof__32__fflags = 0;
    vlSelf->__Vtask_dpi_utof__33__result = 0;
    vlSelf->__Vtask_dpi_utof__33__fflags = 0;
    vlSelf->__Vtask_dpi_ftoi__34__result = 0;
    vlSelf->__Vtask_dpi_ftoi__34__fflags = 0;
    vlSelf->__Vtask_dpi_ftou__35__result = 0;
    vlSelf->__Vtask_dpi_ftou__35__fflags = 0;
    vlSelf->__Vtask_dpi_f2f__36__result = 0;
    vlSelf->__Vtask_dpi_fclss__37__result = 0;
    vlSelf->__Vtask_dpi_fle__38__result = 0;
    vlSelf->__Vtask_dpi_fle__38__fflags = 0;
    vlSelf->__Vtask_dpi_flt__39__result = 0;
    vlSelf->__Vtask_dpi_flt__39__fflags = 0;
    vlSelf->__Vtask_dpi_feq__40__result = 0;
    vlSelf->__Vtask_dpi_feq__40__fflags = 0;
    vlSelf->__Vtask_dpi_fmin__41__result = 0;
    vlSelf->__Vtask_dpi_fmin__41__fflags = 0;
    vlSelf->__Vtask_dpi_fmax__42__result = 0;
    vlSelf->__Vtask_dpi_fmax__42__fflags = 0;
    vlSelf->__Vtask_dpi_fsgnj__43__result = 0;
    vlSelf->__Vtask_dpi_fsgnjn__44__result = 0;
    vlSelf->__Vtask_dpi_fsgnjx__45__result = 0;
    vlSelf->__Vtask_dpi_fadd__46__result = 0;
    vlSelf->__Vtask_dpi_fadd__46__fflags = 0;
    vlSelf->__Vtask_dpi_fsub__47__result = 0;
    vlSelf->__Vtask_dpi_fsub__47__fflags = 0;
    vlSelf->__Vtask_dpi_fmul__48__result = 0;
    vlSelf->__Vtask_dpi_fmul__48__fflags = 0;
    vlSelf->__Vtask_dpi_fmadd__49__result = 0;
    vlSelf->__Vtask_dpi_fmadd__49__fflags = 0;
    vlSelf->__Vtask_dpi_fmsub__50__result = 0;
    vlSelf->__Vtask_dpi_fmsub__50__fflags = 0;
    vlSelf->__Vtask_dpi_fnmadd__51__result = 0;
    vlSelf->__Vtask_dpi_fnmadd__51__fflags = 0;
    vlSelf->__Vtask_dpi_fnmsub__52__result = 0;
    vlSelf->__Vtask_dpi_fnmsub__52__fflags = 0;
    vlSelf->__Vtask_dpi_fdiv__53__result = 0;
    vlSelf->__Vtask_dpi_fdiv__53__fflags = 0;
    vlSelf->__Vtask_dpi_fsqrt__54__result = 0;
    vlSelf->__Vtask_dpi_fsqrt__54__fflags = 0;
    vlSelf->__Vtask_dpi_itof__55__result = 0;
    vlSelf->__Vtask_dpi_itof__55__fflags = 0;
    vlSelf->__Vtask_dpi_utof__56__result = 0;
    vlSelf->__Vtask_dpi_utof__56__fflags = 0;
    vlSelf->__Vtask_dpi_ftoi__57__result = 0;
    vlSelf->__Vtask_dpi_ftoi__57__fflags = 0;
    vlSelf->__Vtask_dpi_ftou__58__result = 0;
    vlSelf->__Vtask_dpi_ftou__58__fflags = 0;
    vlSelf->__Vtask_dpi_f2f__59__result = 0;
    vlSelf->__Vtask_dpi_fclss__60__result = 0;
    vlSelf->__Vtask_dpi_fle__61__result = 0;
    vlSelf->__Vtask_dpi_fle__61__fflags = 0;
    vlSelf->__Vtask_dpi_flt__62__result = 0;
    vlSelf->__Vtask_dpi_flt__62__fflags = 0;
    vlSelf->__Vtask_dpi_feq__63__result = 0;
    vlSelf->__Vtask_dpi_feq__63__fflags = 0;
    vlSelf->__Vtask_dpi_fmin__64__result = 0;
    vlSelf->__Vtask_dpi_fmin__64__fflags = 0;
    vlSelf->__Vtask_dpi_fmax__65__result = 0;
    vlSelf->__Vtask_dpi_fmax__65__fflags = 0;
    vlSelf->__Vtask_dpi_fsgnj__66__result = 0;
    vlSelf->__Vtask_dpi_fsgnjn__67__result = 0;
    vlSelf->__Vtask_dpi_fsgnjx__68__result = 0;
    vlSelf->__Vtask_dpi_fadd__69__result = 0;
    vlSelf->__Vtask_dpi_fadd__69__fflags = 0;
    vlSelf->__Vtask_dpi_fsub__70__result = 0;
    vlSelf->__Vtask_dpi_fsub__70__fflags = 0;
    vlSelf->__Vtask_dpi_fmul__71__result = 0;
    vlSelf->__Vtask_dpi_fmul__71__fflags = 0;
    vlSelf->__Vtask_dpi_fmadd__72__result = 0;
    vlSelf->__Vtask_dpi_fmadd__72__fflags = 0;
    vlSelf->__Vtask_dpi_fmsub__73__result = 0;
    vlSelf->__Vtask_dpi_fmsub__73__fflags = 0;
    vlSelf->__Vtask_dpi_fnmadd__74__result = 0;
    vlSelf->__Vtask_dpi_fnmadd__74__fflags = 0;
    vlSelf->__Vtask_dpi_fnmsub__75__result = 0;
    vlSelf->__Vtask_dpi_fnmsub__75__fflags = 0;
    vlSelf->__Vtask_dpi_fdiv__76__result = 0;
    vlSelf->__Vtask_dpi_fdiv__76__fflags = 0;
    vlSelf->__Vtask_dpi_fsqrt__77__result = 0;
    vlSelf->__Vtask_dpi_fsqrt__77__fflags = 0;
    vlSelf->__Vtask_dpi_itof__78__result = 0;
    vlSelf->__Vtask_dpi_itof__78__fflags = 0;
    vlSelf->__Vtask_dpi_utof__79__result = 0;
    vlSelf->__Vtask_dpi_utof__79__fflags = 0;
    vlSelf->__Vtask_dpi_ftoi__80__result = 0;
    vlSelf->__Vtask_dpi_ftoi__80__fflags = 0;
    vlSelf->__Vtask_dpi_ftou__81__result = 0;
    vlSelf->__Vtask_dpi_ftou__81__fflags = 0;
    vlSelf->__Vtask_dpi_f2f__82__result = 0;
    vlSelf->__Vtask_dpi_fclss__83__result = 0;
    vlSelf->__Vtask_dpi_fle__84__result = 0;
    vlSelf->__Vtask_dpi_fle__84__fflags = 0;
    vlSelf->__Vtask_dpi_flt__85__result = 0;
    vlSelf->__Vtask_dpi_flt__85__fflags = 0;
    vlSelf->__Vtask_dpi_feq__86__result = 0;
    vlSelf->__Vtask_dpi_feq__86__fflags = 0;
    vlSelf->__Vtask_dpi_fmin__87__result = 0;
    vlSelf->__Vtask_dpi_fmin__87__fflags = 0;
    vlSelf->__Vtask_dpi_fmax__88__result = 0;
    vlSelf->__Vtask_dpi_fmax__88__fflags = 0;
    vlSelf->__Vtask_dpi_fsgnj__89__result = 0;
    vlSelf->__Vtask_dpi_fsgnjn__90__result = 0;
    vlSelf->__Vtask_dpi_fsgnjx__91__result = 0;
    vlSelf->__Vtableidx1 = 0;
    vlSelf->__Vtableidx2 = 0;
    vlSelf->__Vtableidx3 = 0;
    vlSelf->__Vtableidx4 = 0;
    vlSelf->__Vtableidx5 = 0;
    vlSelf->__Vtableidx6 = 0;
    vlSelf->__Vtableidx7 = 0;
    vlSelf->__Vtableidx8 = 0;
}
