FROM ubuntu:22.04

# Install dependencies
RUN apt-get update
# RUN apt-get -y install build-essential wget vim libtinfo5 pip libboost-all-dev libopenblas-dev
RUN apt-get -y install build-essential clang wget git libtinfo5 pip uuid-dev libboost-all-dev libopenblas-dev
RUN pip install numpy
RUN mkdir /vortex

# Mount repository
ARG VORTEX_ROOT
ADD $VORTEX_ROOT /vortex
WORKDIR /vortex

# Install toolchain
RUN chmod +x ./ci/toolchain_install.sh
RUN ./ci/toolchain_install.sh --all

WORKDIR ..
RUN rm -rf ./vortex

RUN echo "export VERILATOR_ROOT='/opt/verilator/'" >> ~/.bashrc
RUN echo "export RISCV_TOOLCHAIN_PATH=/opt/riscv-gnu-toolchain" >> ~/.bashrc
RUN echo "export LLVM_POCL=/opt/llvm-pocl" >> ~/.bashrc
RUN echo "export LLVM_VORTEX=/opt/llvm-vortex" >> ~/.bashrc
RUN echo "export SV2V_PATH=/opt/sv2v" >> ~/.bashrc
RUN echo "export YOSYS_PATH=/opt/yosys" >> ~/.bashrc
RUN echo "export PATH='/opt/yosys:/opt/sv2v:/opt/verilator/bin:${PATH}'" >> ~/.bashrc
RUN echo "export POCL_CC_PATH=/opt/pocl/compiler" >> ~/.bashrc
RUN echo "export POCL_RT_PATH=/opt/pocl/runtime" >> ~/.bashrc
RUN echo "alias python=python3" >> ~/.bashrc
